### ISSUE TITLE
Octocat is too overpowered

### ISSUE THREAD

**Issue by utybo** [octocat/Hello-World#161]
I found out that the Octocat is too cute/overpowered/nice/whatever-you-want-it-to-be. It needs nerf. Or more cuteness. You guys see.

**Comment by ghost** [comment]
Love you octocat... I need you to bunny bunny...

**Comment by DonTheorist** [comment]
lol :)

yours sincerely

[image: --]
Dane Wilkinson
[image: http://]about.me/dane.wilkinson
http://about.me/dane.wilkinson
