### ISSUE TITLE
Impedit assumenda quidem sit reiciendis.

### ISSUE THREAD

**Issue by firebot-test** [octocat/Hello-World#328]
*Opened via [firebot](http://localhost:12000/), sent by Mary Davenport (le@lenny.com)*

Officia sed explicabo exercitationem alias corrupti tempore. Perspiciatis repellat tempora iusto quia dicta.

**Comment by Erinaaaaaaa** [comment]
looks like you're opening a lot of issues through firebot. Would you mind
creating your own repo to work in ?

Le mer. 22 févr. 2017 01:01, firebot-test <notifications@github.com> a
écrit :

**Comment by RedStarThrower** [comment]
Ha! More like _firedbot_...

**Comment by Allison80** [comment]
🙌🏻🤣

**Comment by Erinaaaaaaa** [comment]
👌

**Comment by firebot-test** [comment]
Oops 🤖 💩
