### ISSUE TITLE
123

### ISSUE THREAD

**Issue by MadL0rd** [octocat/Hello-World#588]

**Comment by MadL0rd** [comment]
![cogwheel_settings_icon_124177 (1)](https://user-images.githubusercontent.com/26849571/70322305-d0e41600-183a-11ea-8f59-1813c35b3cad.png)
test

**Comment by MadL0rd** [comment]
[Code_review_Tekutov_November_2019.docx](https://github.com/octocat/Hello-World/files/3932176/Code_review_Tekutov_November_2019.docx)

**Comment by email2224** [comment]
I need a description MadL0rd
