### ISSUE TITLE
Hello World in all programming languages

### ISSUE THREAD

**Issue by mwumvaxgh** [octocat/Hello-World#7]
It could be a good idea to add code snippets for hello world in all programming languages. So that its a kind of "one-stop-shop" for a simple Hello World program

**Comment by mwumvaxgh** [comment]
Oh wait, another useful feature could be to add "How To Set Up" the environment for the different languages.
A good resource " http://www.roesler-ac.de/wolfram/hello.htm "

**Comment by arcecio** [comment]
hi there!

**Comment by tarebyte** [comment]
Looks good to me!

**Comment by brianykim** [comment]
LGTM

**Comment by arcecio** [comment]
Awesomo 4000 rules!

**Comment by arcecio** [comment]
Awesomo 4000 rules yo!

**Comment by maximevaillancourt** [comment]
Nice! :)

**Comment by nagarakesh4** [comment]
cool!

**Comment by sasanikolic90** [comment]
We're already using GraphQL for Drupal. Cool stuff 👍

**Comment by JacobBennett** [comment]
poop 💩

**Comment by diegovillacis10** [comment]
Great!

**Comment by yongzhihuang** [comment]
Very good 👍

**Comment by ericnkatz** [comment]
I'm cheating but thanks mark! :)

**Comment by byennen** [comment]
😄 awesome! thanks for the demo!!

**Comment by moisesnandres** [comment]
nice!

**Comment by crash7** [comment]
Thanks for the demo Mark! 😄

**Comment by nandub** [comment]
This is awesome

**Comment by metalvegetarianoprogresivo** [comment]
Awesome demo! Looking forward to start working with GraphQL.

>Edgardo se la come.

**Comment by kasiriveni** [comment]
This is awesome 👍

**Comment by kylekthompson** [comment]
Hello GraphQL :sparkles: :tada: :confetti_ball:

**Comment by daisyramos317** [comment]
Thanks for the session! Pagination demo was helpful

**Comment by iology** [comment]
LOL

**Comment by lhao75540-ctrl** [comment]
Nice work!
